basePath: /api
info:
  contact: {}
  description: This is a sample server for WhereIsEveryone
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: WhereIsEveryone
  version: "1.0"
paths:
  /update:
    post:
      responses: {}
      summary: updates user location
      tags:
      - Location
swagger: "2.0"
